# Generated by Django 4.1.2 on 2022-11-03 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_post_created_by'),
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together={('post',)},
        ),
        migrations.RemoveField(
            model_name='comment',
            name='order',
        ),
    ]
