# Generated by Django 4.1.2 on 2022-10-14 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_tag',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
