# Generated by Django 4.1.2 on 2022-10-10 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_post_tag_tag_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(related_name='tags', to='post.tag'),
        ),
    ]
