# Generated by Django 3.2.16 on 2022-11-06 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20221106_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='updated',
            field=models.BooleanField(default=False),
        ),
    ]
