# Generated by Django 4.1.2 on 2022-10-10 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_alter_post_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='tag',
            field=models.ManyToManyField(related_name='tag_by_comment', to='post.tag'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(related_name='tag_by_post', to='post.tag'),
        ),
    ]
