# Generated by Django 3.2.16 on 2022-11-06 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_comment_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='updated',
            field=models.BooleanField(null=True),
        ),
    ]
