# Generated by Django 4.1.2 on 2022-10-10 12:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_alter_comment_tag_alter_post_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='create_tag',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='create_tag',
            field=models.CharField(default='default', max_length=200),
            preserve_default=False,
        ),
    ]
