# Generated by Django 4.1.2 on 2022-10-11 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_alter_comment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='summary_for_list_api',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
