# Generated by Django 4.1.2 on 2022-10-20 16:50

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(storage='../', upload_to=users.models.upload_to),
        ),
    ]
