# Generated by Django 4.1.2 on 2022-10-28 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='followers_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='following_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='post_count',
            field=models.IntegerField(null=True),
        ),
    ]
