# Generated by Django 4.1.2 on 2022-10-28 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_followers_count_user_following_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='followers_count',
        ),
        migrations.RemoveField(
            model_name='user',
            name='following_count',
        ),
        migrations.RemoveField(
            model_name='user',
            name='post_count',
        ),
    ]
