# Generated by Django 4.1.1 on 2022-10-30 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("medium", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tagtopostcomment",
            name="comment",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="medium.comment",
            ),
        ),
        migrations.AlterField(
            model_name="tagtopostcomment",
            name="tag",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="medium.tag"
            ),
        ),
    ]
