# Generated by Django 4.1.1 on 2022-10-30 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("medium", "0002_alter_tagtopostcomment_comment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tagtopostcomment",
            name="post",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="medium.post"
            ),
        ),
    ]
