# Generated by Django 4.1.1 on 2022-10-26 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_tag_comment_tags_post_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
        migrations.AddField(
            model_name='tag',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='comment_tag', to='blog.comment'),
        ),
        migrations.AddField(
            model_name='tag',
            name='posts',
            field=models.ManyToManyField(blank=True, related_name='post_tag', to='blog.post'),
        ),
    ]
