# Generated by Django 4.1.1 on 2022-10-26 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_comment_tags_remove_post_tags_tag_comments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='tags', to='blog.comment'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='posts',
            field=models.ManyToManyField(blank=True, related_name='tags', to='blog.post'),
        ),
    ]
