# Generated by Django 4.1.2 on 2022-11-05 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment", old_name="create_by", new_name="created_by",
        ),
        migrations.RenameField(
            model_name="post", old_name="create_by", new_name="created_by",
        ),
    ]
