# Generated by Django 4.1.2 on 2022-11-05 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_alter_comment_options_alter_post_options"),
    ]

    operations = [
        migrations.AlterModelOptions(name="comment", options={"ordering": ["id"]},),
        migrations.AlterModelOptions(name="post", options={"ordering": ["id"]},),
    ]
