# Generated by Django 4.1.2 on 2022-11-03 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_alter_user_options_user_date_joined_user_first_name_and_more"),
    ]

    operations = [
        migrations.DeleteModel(name="User",),
    ]
