# Generated by Django 4.1.2 on 2022-11-03 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0008_delete_myuser"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment", options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="post", options={"ordering": ["-created_at"]},
        ),
    ]
