# Generated by Django 4.1.2 on 2022-10-29 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='claps',
            field=models.BigIntegerField(default=0),
        ),
    ]
