# Generated by Django 4.1.2 on 2022-10-31 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='claps',
        ),
    ]
