# Generated by Django 4.1.2 on 2022-11-05 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0004_alter_tag_content'),
        ('posts', '0006_post_tags_tagtopost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(through='posts.TagToPost', to='tags.tag'),
        ),
    ]
