# Generated by Django 4.1.2 on 2022-10-22 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='is_updated',
            field=models.BooleanField(default=False),
        ),
    ]
