# Generated by Django 4.1.2 on 2022-10-16 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='n_min_read',
            field=models.IntegerField(null=True),
        ),
    ]
