# Generated by Django 4.1.2 on 2022-10-28 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_alter_comment_is_updated_alter_comment_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='clapse_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='comment_count',
            field=models.IntegerField(null=True),
        ),
    ]
