# Generated by Django 4.1.2 on 2022-10-28 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_post_clapse_count_post_comment_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='clapse_count',
        ),
        migrations.RemoveField(
            model_name='post',
            name='comment_count',
        ),
    ]
