# Generated by Django 4.1.2 on 2022-11-04 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='tagatpost',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='tagatpost',
            name='post',
        ),
        migrations.DeleteModel(
            name='TagAtComment',
        ),
        migrations.DeleteModel(
            name='TagAtPost',
        ),
    ]
