# Generated by Django 4.1.2 on 2022-11-04 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_tag_alter_tagatpost_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='id',
        ),
        migrations.AlterField(
            model_name='tag',
            name='content',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
