# Generated by Django 4.1.2 on 2022-11-05 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0003_remove_tag_id_alter_tag_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='content',
            field=models.SlugField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
