# Generated by Django 4.1.3 on 2022-11-06 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MediumBlog', '0003_rename_customuser_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
