# Generated by Django 4.1.3 on 2022-11-06 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MediumBlog', '0004_alter_comment_updated_at_alter_post_published_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_authorized',
            field=models.BooleanField(default=False),
        ),
    ]
