# Generated by Django 4.1.3 on 2022-11-06 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MediumBlog', '0006_user_subscribers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='post',
            name='published_at',
        ),
    ]
