# Generated by Django 4.1.3 on 2022-11-07 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MediumBlog', '0008_remove_user_bookmarks_remove_user_clap_comments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_authorized',
            field=models.BooleanField(default=True),
        ),
    ]
