# Generated by Django 4.1.1 on 2022-11-01 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medium', '0002_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='cid',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='pid',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
