# Generated by Django 4.1.1 on 2022-11-04 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medium', '0005_rename_cid_comment_comment_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('content', models.CharField(blank=True, max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='TagToPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medium.post')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medium.tag')),
            ],
        ),
        migrations.CreateModel(
            name='TagToComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medium.comment')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medium.tag')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='tag',
            field=models.ManyToManyField(through='medium.TagToComment', to='medium.tag'),
        ),
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(through='medium.TagToPost', to='medium.tag'),
        ),
    ]
