# Generated by Django 4.1.1 on 2022-11-05 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medium', '0007_comment_likes_post_likes_alter_comment_post_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tagtocomment',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='tagtopost',
            name='created_at',
        ),
    ]
